ALTER TABLE topics ADD COLUMN draft BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE topics ADD COLUMN sticky BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE topics ADD COLUMN off_front BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE topics ADD COLUMN resolved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE topics ADD COLUMN minor BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX topics_section_sticky_idx
    ON topics (section_id, sticky DESC, created_at DESC);
